prog:source.o source_lot1.o source_lot2.o source_lot3.o source_lot4.o source_lot5.o main.o source_sous_menu.o
	gcc source.o source_lot1.o source_lot2.o source_lot3.o source_lot4.o source_lot5.o source_sous_menu.o main.o -o prog -g -lSDL -lSDL_image -lSDL_ttf -lSDL_mixer
source.o:source.c
	gcc -c source.c 
source_lot1.o:source_lot1.c
	gcc -c source_lot1.c
source_lot2.o:source_lot2.c
	gcc -c source_lot2.c 
source_lot3.o:source_lot3.c
	gcc -c source_lot3.c 
source_lot4.o:source_lot4.c
	gcc -c source_lot4.c 
source_lot5.o:source_lot5.c
	gcc -c source_lot5.c 
source_sous_menu.o:source_sous_menu.c
	gcc -c source_sous_menu.c 
main.o:main.c
	gcc -c main.c
